xaoxuu/hexo-theme-stellar

_config.yml, layout/_partial/head.ejs, layout/_partial/main/post_list/post_card.ejs, layout/post.ejs
「赫蹏」是專為中文網頁內容設計的排版樣式增強。它基於通行的中文排版規範，可為網站的讀者帶來更好的內容閱讀體驗。
目前只套用在文章和文章卡片的摘要上。
https://sivan.github.io/heti/
E2E basic test passed.
=> feat: 加入 heti 排版樣式增強 CSS 的支援

layout/_partial/head.ejs, source/js/main.js
Heti 的 autoSpacing 是透過監聽 DOMContentLoaded 實作的——若採用 async 的載入方式，會導致註冊 autoSpacing 的 DOMContentLoaded handler 時，DOMContentLoaded 早已觸發完畢，亦即：.autoSpacing() 會失效。
=> fix(plugin/heti): load stellar's JS code ASAP

source/css/_common/highlight.styl
Make `Rust` can be shown correctly when the code block is marked as `rs`.
To match which `js` appears as. Besides, `TypeScript` may be too long for some cases, imo. Besides, added `ts` as the alias of `TypeScript`.
=> Add Rust & Rename TypeScript to TS

_config.yml
将 Waline 评论系统的自带表情从 1.0.1 升级到了 1.1.0，并加入了新表情 “哔哩哔哩小黄脸”，可参考 https://waline.js.org/guide/client/emoji.html ，实测新版本表情包可用。
=> 升级 Waline 评论系统的自带表情

_config.yml, layout/_partial/plugins/comments/waline/script.ejs
之前评论系统 Waline 只能使用 Base64 编码的方式上传图片，体积限制在 128 KB，略有不便。
故新增图床为图片上传可选项，适配了兰空图床V1、V2版本（两版本 Api 略有不同），可以有选择性地启用图床，或者使用默认的 Base64，皆测试运行正常。
我目前选择的是兰空图床V2，可实际体验：[https://www.shifeiti.com/about/](https://www.shifeiti.com/about/)
=> Waline 新增图床为图片上传可选项

layout/_partial/main/article/article_footer.ejs
当设置如下时，微信二维码分享链接尾部会带 `index.html`（permalink 不带 index.html），与其他三种分享方式的链接不统一，且通过扫码进入的网页会是一个“新的”评论区：
```
pretty_urls: # 改写 permalink 的值来美化 URL
trailing_index: false # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除。
```
二维码分享链接无“新的”评论区这种现象：
且与其他三种分享方式的链接相统一：
经测试，当设置 permalink 带 index.html 时，修改后的二维码链接依旧表现正常，且与其他三种分享方式的链接相统一，不再赘述。
=> 统一微信二维码分享链接

_config.yml, layout/_partial/scripts/index.ejs, source/js/main.js
目前如果站点部署在多级目录下, loadScript会丢失很多js, search.json也会丢失
丢失的JS思路是修复js的引用方法`loadScript`
在script的src添加'<%- config.root %>'可以基于站点目录申请资源,  而非直接去域名下申请资源.
`<script src="/js/xxx.js"></script>`  to  `<script src="/部署目录/js/xxx.js"></script>`
获取search.json文件不在ejs不能使用hexo全局变量url, 我只能想到主题配置search.local_search下增加一个root来配置资源位置.
=> [fix] loadScript, search

layout/_partial/head.ejs
解决 [issue](https://github.com/xaoxuu/hexo-theme-stellar/issues/278)，增加 keywords，支持多种设置方法。
front-matter 中设置的 `keywords` > front-matter 中设置的 `tags` > 根目录下 _config.yml 中设置的 `keywords` > 返回空字符串
```
---
tags: [tag1, tag2, Tag3]
keywords: keyword1,Keyword2,keyword3
---
```
结果：
```
<meta name="keywords" content="keyword1,Keyword2,keyword3">
```
```
tags: [tag1, tag2, Tag3]
```
结果：
```
<meta name="keywords" content="tag1,tag2,Tag3">
```
或
```
---
tags:
- Tag1
- tag2
- Tag3
---
```
结果：
```
<meta name="keywords" content="Tag1,tag2,Tag3">
```
对应无法自定义 front-matter 及 front-matter 中未设置 keywords、tags 的这两种页面。
```
keywords: K1,k2,k3
```
结果：
```
<meta name="keywords" content="K1,k2,k3">
```
=> 增加 keywords

_config.yml, layout/_partial/main/copycode.ejs, layout/layout.ejs
新功能： 添加代码块复制代码功能，可自行添加配置，CodeBlock.show_copy为true时显示
新增配置：
CodeBlock:
show_copy: true # 是否显示复制按钮
default_text: 'copy' # 复制按钮默认文字
success_text: 'copied' # 复制按钮成功时的文字
=> feat: 代码块复制代码 #268

scripts/filters/index.js
个人不建议 markdown 图片 alt 文本作为图片标题，很多笔记软件都是会自动填充 alt 文本的（比如 Typora），个人认为 alt 文本更适合在图片丢失或无网络情况下用来提示此处有图片。而目前语雀、思源笔记等笔记软件，都是以 markdown 图片 title 作为图片标题的。
scripts\filters\index.js 修改 markdown 图片解析规则：解析 alt 文本为图片标题改为解析 title 文本为图片标题
=> ✨[feat] markdown title作为图片标题

source/css/_layout/partial/footer.styl, source/css/_layout/sidebar/menu.styl, source/css/_layout/widgets/list.styl
- 修复侧边栏最近文章列表的行高
- 现在诸如`g` `y`等字符也能完整显示了，而不是底部被裁切
- 美化navbar中高亮(active)元素的样式
- 侧边栏的导航栏中，图标底部的下划线具有和图标相同的颜色，而不是普通文本颜色
- 增加了页脚sitemap元素的圆角大小
- 具有和主页顶部导航栏、超链接相同的值(4px)
=> [opt] navbar, sidebar-list, footer

layout/_plugins/tianli_gpt.ejs
wiki项目的 `layout` 变成了 `page` 导致GPT `field` 参数设置 `wiki` 失效
=> [fix] tianli_gpt layout

layout/_plugins/fancybox.ejs, scripts/tags/lib/image.js, source/css/_plugins/fancybox.styl
Tried to fix xaoxuu#442.
When using the `image` tag plugin, user can use another image's url as the value of `fancybox` argument. This image will be used in fancybox's popup view.
``` ejs
{% image thumbnail-src alt fancybox:hd-src %}
```
Implementation details:
When `fancybox` is set to `true` (or `false`), nothing changed.
Otherwise, wrap the `<img>` by a fancybox-enabled `<a>` element, i.e.:
``` html
<a data-fancybox data-caption="alt" href="hd-src">
</a
```
=> [feat] fixes xaoxuu#442: img fancybox supports providing a different image for popup

layout/page.ejs
在文档 <https://xaoxuu.com/wiki/stellar/wiki-settings/> 中提到，wiki 页面可以设置显示 license 或 分享，但按照文档设置后并无法显示出来。
此 PR 修复该问题。
=> [fix] render article footer in wiki pages

_config.yml, layout/_partial/comments/artalk/script.ejs
修复以下问题：
1、低版本的 artalk js 无法对接高版本的 artalk 后端，升级配置文件中的版本；
2、模板中向 artalk 传递 site 名称使用了 `<%=` 转义会导致 artalk 无法对应站点，改用 `<%-` 解决。
例如我的博客名叫 `Frytea's Blog` ，但是在 artalk 看到请求的是类似 `Frytea&#39;s Blog` 导致 artalk 无法找到对应名字的站点，最终得到 404 错误。
```bash
Error: 未找到站点：`Frytea&#39;s Blog`，请在控制台创建站点
```
- references: ejs docs: https://ejs.co/#install
---
Fix the following issues:
1. Older versions of artalk js cannot connect to newer versions of artalk backend, upgrade the version in the configuration file;
2. Passing the site name to artalk in templates using `<%=` for escaping will cause artalk to not recognize the site correctly, use `<%-` instead.
For example, if my blog is named 'Frytea's Blog', but in artalk I see requests like 'Frytea&#39;s Blog', which causes artalk to be unable to find the corresponding …
=> fix(stellar-artalk): bump version, fix site name escape

layout/_partial/main/article/article_footer.ejs
`article_footer` 里 wechat 分享按钮的地方，`&quot;` 少写了一个分号。此 PR 修复该问题。
这个问题会导致通过 terser 对 html 内的 js 压缩的时候语法解析失败。
复现方式：
在 `_config.stellar.yml` 中 `article.share` 配置中确保添加了 `wechat`，开启 wechat 分享按钮。
以基于 `@uiolee/hexo-htmlnano` 插件为例，对构建物进行压缩：
``` bash
pnpm add @uiolee/hexo-htmlnano cssnano postcss terser svgo
hexo generate
```
进行压缩的时候，terser 会报错：
``` log
SyntaxError: Unterminated string constant
at js_error (/node_modules/.pnpm/terser@5.31.0/node_modules/terser/dist/bundle.min.js:536:11)
at parse_error (/node_modules/.pnpm/terser@5.31.0/node_modules/terser/dist/bundle.min.js:672:9)
at /node_modules/.pnpm/terser@5.31.0/node_modules/terser/dist/bundle.min.js:1043:36
at Object.next_token [as input] (/node_modules/.pnpm/terser@5.31.0/node_modules/terser/dist/bundle.min.js:1076:40)
......
```
并导致所有开启了 …
=> [fix] fix typo - missing `;` for `&quot;`

_config.yml, layout/_partial/comments/artalk/script.ejs, layout/_partial/comments/beaudar/script.ejs, layout/_partial/comments/giscus/script.ejs, layout/_partial/comments/twikoo/script.ejs, layout/_partial/comments/utterances/script.ejs, layout/_partial/comments/waline/script.ejs, source/js/main.js
支持评论区进入视口后懒加载，通过 ``theme.comments.lazyload`` 控制，默认关闭，向下兼容。
``querySelectorAll`` 查询复数 ``id``，存在 ``id`` 重复的元素本身并不合理。
``DOMContentLoaded`` 事件可以使用 ``type="module"`` 的 ``<script>`` 取代，并且后者不会泄露任何作用域变量至全局。
``var`` 和 ``let`` 混用的问题，不变的常量用 ``const`` 定义是最好的，有内存优化。
=> feat: 评论区视口懒加载

_config.yml, scripts/tags/lib/quot.js, source/css/_components/md.styl, source/css/_components/tag-plugins/quot.styl
`hexo-renderer-marked` 和 `hexo-renderer-markdown-it-plus` 为标题添加的锚点按钮的类名不一致，主题只对应 Hexo 默认渲染器做了适配。
通过更改 CSS 选择器，可以使多个渲染器生成的页面具有相同的标题样式，解决 #476 的问题。
同时，移除了 `{% quot %}` 标签中未使用的锚点按钮，进一步精简了代码，便于后期维护。
=> [fix] multi renderer support, resolve #476

layout/_partial/main/article/related_posts.ejs
解决 `theme.article.related_posts.title` 配置项无效的问题。
=> [fix] related_posts title

scripts/tags/lib/video.js, source/css/_components/tag-plugins/media.styl
- 修复了设置宽度后视频不居中的问题
- 修复了bilibili视频无法放入grid标签的问题
建议官方文档中补充video标签的ratio、type参数的说明。
=> [fix] video tag

layout/_partial/main/navbar/nav_tabs_blog.ejs
群友在 nginx 服务器上部署遇到问题，首页导航栏的“标签”“分类”等按钮链接应当尾随斜杠，否则默认配置下无法访问。
另外，也可添加以下 nginx 配置解决问题。
```nginx
index index.html;
location / {
try_files $uri $uri.html $uri/ =404;
}
error_page 404 /404.html;
```
=> fix: link path in nav_tabs_blog.ejs

scripts/tags/lib/video.js
共有两处修改：
1. 对 `iframe` 添加了 `border:none` 干掉了垃圾 iframe 自带的一层白边，还挺影响深色模式的观感的。
去除前：
2. 根据 [Chrome 的老旧政策](https://stackoverflow.com/questions/40685142/youtube-autoplay-does-not-work-with-iframe) ，自动开播需要追加 `mute=1` 以静音。
=> fix: youtube iframe

scripts/generators/search.js
当 skip_search 为空时 patterns 不可迭代
=> [fix] skip_search is not iterable

scripts/generators/notebooks.js
notebooks不设置时生成额外的空 `notebooks/` 页面 #507
=> [fix] notebooks undefined

layout/_partial/head.ejs, layout/_partial/scripts.ejs
由于在hexo的_config文件中定义url的root选项，造成theme无法加载theme中css,js资源文件的bug
通过在head.ejs与script.ejs文件的包括语句增加url_for函数解决
=> [fix]: 修复hexo路由改变造成无法正常加载theme资源文件的bug

source/css/_components/tag-plugins/tabs.styl
fix: #308 
除开tabs标签，其他的容器类标签（folding folder等）在嵌套mermaid的时候有可能会导致语法错误，例如
{% folding mermaid示例 %}
```mermaid
graph LR
A --> B
B --> C
C --> D
```
{% endfolding %}
由于部分mermaid图表依赖换行符与缩进来解析不同的命令和结构，而 `.split('\n').join('')` 删除了所有的换行符，Mermaid 的解析器将无法正确地理解上述代码，因为它会被压缩成一行
```
graph LRA --> BB --> CC --> D
```
=> [fix] tabs mermaid syntax error

scripts/generators/notebooks.js
`notebooks.tree` is an object, not array.
修复在 notebooks generator 中，之前对 `notebooks.tree` 是否为空的错误判定。
最初版本 `notebooks.tree.length === 0` 会导致没有 notebook 的时候，拦不住。
后一个版本 `notebooks.tree.length === undefined` 会导致有 notebooks 的时候也直接返回。
因为 `notebooks.tree` 是对象而不是数组，取 `length` 始终返回 `undefined`。
=> fix(notebooks): fix bug in notebooks generator

source/css/_plugins/katex.styl
之前 katex 的 `overflow` 样式是设置在 `.md-text p.katex-block .katex-display` 上的，在有些时候会出现当鼠标在公式那里上下滚动的时候，公式会上下微小浮动，如图：
把 `overflow` 改在 `.md-text p.katex-block` 上没有这个问题。
=> fix: refine katex overflow style

scripts/tags/lib/sites.js
Change`https://api.vlts.cc/screenshot?url=`to`https://image.thum.io/get/width/1280/crop/720/`
---
原来的`https://api.vlts.cc/screenshot?url=`似乎容易超出用量，感觉可以更换成这个`https://image.thum.io/get/width/1280/crop/720/`
=> [fix]更换 sites 截图提供商

scripts/tags/lib/folding.js
`ctx.render.renderSync({text: content, engine: 'markdown'})`对图片的渲染结果为：
```html
<img
src="https://example.com/a.png"
alt="description" />
```
将`\n`替换为空字符导致其变为
```html
<imgsrc="https://example.com/a.png"alt="description" />
```
经过处理lazyload的filter又会变为
```html
```
**将`\n`替换为空格可解决问题**
另外，Windows系统下未出现过此问题，但Github Action和我的Fedora都出现此问题，原因未知，可能和不同系统换行符差异有关
=> [fix] 修复folding标签渲染异常问题

layout/_plugins/mermaid.ejs
在暗色模式下，Mermaid 图表未能自动切换为 `dark` 主题，仍然使用浅色，导致显示异常。
经查是模板中 EJS (themes/stellar/layout/_plugins/mermaid.ejs) 判断用的是：
```js
"<%- theme.style.darkmode %>" == "auto" && ...
```
但实际配置项是：
```yaml
style:
prefers_theme: auto
```
修改为了：
```js
"<%- theme.style.prefers_theme %>" == "auto" && ...
```
=> [fix] 修复mermaid暗色配置项的一个小问题

scripts/filters/pretty_urls.js
现有的原始内容输出列表没包括js，css，会导致用户在source目录中存放的js，css被错误处理成json形式
=> [fix]pretty_urls.js

_config.yml, layout/_plugins/mathjax.ejs
在使用 MathJax v2 时遇到 Chrome 浏览器无法正确显示特定数学符号的问题。虽然可以通过修改 `plugins.mathjax.js` 配置来替换为 v3 版本的 CDN 链接，但由于 v2 和 v3 的配置语法完全不同，仅仅替换 CDN 链接无法正常工作，还需要同步更新相应的初始化脚本。
本 PR 新增对 MathJax v3 的原生支持，通过以下方式解决上述问题：
- **新增配置选项** `plugins.mathjax.v3`：布尔值，控制使用 MathJax v2 或 v3 版本
- **自动版本切换**：根据 `v3` 配置自动选择对应的初始化脚本和 CDN 链接
- **配置对等性**：v3 版本的配置功能与 v2 版本完全对等，支持相同的数学公式渲染需求
- **默认行为不变**：未设置 `v3` 选项时，默认使用 v2 版本，保持原有行为
- **现有配置不受影响**：已配置 MathJax 的博客无需修改任何设置即可正常工作
```yaml
plugins:
mathjax:
enable: true
v3: true  # 新增选项，设为 true 使用 v3 版本
js: https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js # 启用 v3 时需指定 js
```
=> [feat] 增加 mathjax v3 的支援
