xaoxuu/hexo-theme-stellar

languages/zh-TW.yml

I love this theme, so I made a few improvements to this :) Hope this project becomes better!
---
我喜歡這個主題，所以我做了一些微小的改善 :) 希望這個專案能夠越來越好！

l10n(languages/zh-TW): localization

---

layout/_partial/main/article/related_posts.ejs

设置 maxCount: theme.article.related_posts.max_count

设置 maxCount 为变量

---

_config.yml

swiper版本锁定

---

_config.yml
layout/_partial/scripts/index.ejs
source/js/main.js

- https://fancyapps.com/docs/ui/fancybox/

Add Fancybox

---

source/css/_common/cap.styl
source/css/_layout/partial/footer.styl
source/css/_layout/sidebar/sidebar.styl

修复firfox浏览器中显示侧边栏滚动条的问题

---

_config.yml
source/css/_custom.styl
source/css/_plugins/comments/twikoo.styl
source/css/_plugins/comments/waline.styl

自定义主题色&网站字体大小

---

_config.yml

由于疏忽，[PR237](https://github.com/xaoxuu/hexo-theme-stellar/pull/237) 的说明部分写错了两处，已更正。

更正 PR237 中说明部分的错误

---

scripts/tags/lib/folding.js

doc: update folding doc

---

_config.yml

参考https://github.com/KaTeX/KaTeX#starter-template

更新katex的integrity值

---

_config.yml
layout/mermaid.ejs
layout/post.ejs
source/css/_plugins/index.styl
source/css/_plugins/mermaid.styl

使用hexo-filter-mermaid-diagrams插件增加对mermaid流程图的支持，详见主题_config.yml文件的使用说明

增加对mermaid流程图的支持

---

layout/_partial/main/post_list/paginator.ejs

fix: 分类和标签页不显示分页器

---

layout/mermaid.ejs
source/css/_plugins/mermaid.styl

mermaid darkmode

---

_config.yml
layout/_plugins/tianli_gpt.ejs
source/css/_plugins/tianli_gpt.styl

- 更换前端为 qxchuckle/Post-Summary-AI 项目

fix tianli_gpt

---

source/css/_plugins/mermaid.styl

center mermaid

---

_config.yml
layout/_partial/comments/waline/script.ejs

waline v3.x

---

source/js/plugins/copycode.js

[fix] error handler for codeCopyBtn

---

_config.yml
layout/_plugins/search/algolia_search.ejs
source/js/search/algolia-search.js

Test Page: https://weekdaycare.top/

[feat] algolia_search

---

layout/_plugins/swiper.ejs

[fix] swiper cycle invalid

---

layout/_partial/comments/layout.ejs

wiki项目中设置 `comments: false` 不生效

[fix] proj.comments false

---

layout/_partial/head.ejs
source/css/_defines/func.styl
source/css/_defines/theme.styl

[fix] #477 bad appearence with no prefers-color-scheme

---

scripts/tags/lib/video.js

https://github.com/xaoxuu/hexo-theme-stellar/discussions/226#discussioncomment-9685505
* 添加支持适配youtube的iframe嵌入 ，可设置最大宽度和是否自动播放

feat: add youtube video

---

layout/_partial/comments/artalk/script.ejs
layout/_partial/comments/twikoo/script.ejs
layout/_partial/comments/waline/script.ejs
layout/_partial/scripts.ejs

fix: load script synchronously

---

source/js/services/memos.js

memos最近的更新数据表发生变动，导致API接口与字段参数变动与缺失。相关issue #474 
且未备份情况下版本回退不易，[回退参考](https://github.com/orgs/usememos/discussions/3522)
不知道memos未来会不会整出什么其它烂活，建议memos service代码进行建议版本管理
[新版获取个人memos列表](https://memos.thatcoder.cn/api/v1/memos?filter=creator%3d%3d%27users%2F1%27&pageSize=10): `/api/v1/memos?filter=creator=='users/1'&pageSize=6`
[新版获取个人信息](https://memos.thatcoder.cn/api/v1/users/1): `/api/v1/users/1`

[feat] support memos Version management

---

layout/_partial/head.ejs
scripts/generators/search.js

- Added checks to confirm that tags and categories are arrays before iterating over them.

fix: ensure tags and categories are arrays before iterating

---

scripts/tags/lib/box.js
scripts/tags/lib/folders.js
scripts/tags/lib/folding.js

[fix] mathjax render

---

scripts/events/lib/doc_tree.js

[fix] empty wiki  delete in loop
